# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#Solution Below

MAX = 10
a = 1
b = 2
count = 0

while count < MAX:
    print(a)
    c = a + b
    #update values, dont change below sequence
    a = b
    b = c
    count += 1


    # print("length is: ", len(lst))


    # print("now list is :", lst, end = '')
